djangoProject1/dogs/urls.py
from django.urls import path
from . import views
app_name = 'dogs'
urlpatterns = [
#     lostpost views
    path('', views.home, name='home'),
    path('login', views.login, name="login"),
    path('logout', views.logout, name="logout"),

    path('logout2', views.logout2, name="logout2"),




#     urls and views for the rest of the web app pages
    path('events', views.events, name='events'),
    path('parkrules', views.parkrules, name='parkrules'),
    path('searchresults', views.searchresults, name='searchresults'),
    path('searchresultsblank', views.searchresultsblank, name='searchresultsblank'),

    # PROJECT5 updates made
    path('posts', views.lostpost_list, name='lostpost-list'),
    path('posts_date', views.lostpost_list_date, name='lostpost-list-date'),
    path('posts_date2', views.lostpost_list_date2, name='lostpost-list-date2'),
    # uses the ID of the class instance to populate the story detail page dogs/stories/1 or 2
    path('postdetail/<int:story_id>', views.lostpost_story_detail, name='story-detail'),

    # urls and views for editing and deleting the DETAILS of a post
    path('add', views.add, name='add'),

    path('edit/<int:story_id>', views.lostpost_story_detail_edit, name='story-edit'),
    path('delete/<int:story_id>', views.lostpost_story_detail_delete, name='story-delete'),


#     PROJECT 5 URLS ADDED USING AJAX FROM VIEWS PY
    path('posts/delete', views.lostpost_delete, name='story-deletefromdatabase'),
    path('posts/edit', views.lostpost_edit, name='story-editfromdatabase'),

    # PROJECT5 SORT
    path('posts/sort', views.list_sort_ajax, name='list_sort_ajax'),

# PROJECT5 AJAX USED IN LIST.JS
    path('posts/upvote', views.lostpost_upvote, name='story-upvote'),
    path('posts/downvote', views.lostpost_downvote, name='story-downvote'),

    path('posts/contact', views.view_contact_ajax, name='view-contact-ajax'),
    path('posts/follow', views.view_follow_ajax, name='view-follow-ajax'),
]

djangoProject1/templates/dogs/base.html
{%  load static %}

<!doctype html>
<html lang="en">
  <head>
      <meta charset="utf-8">
<!--Responsive design to replace the original global css file to adjust between desktop and mobile-->
      <meta name="viewport" content="width=device-width">
      <title>Falls Church Dog Park | {% block page-title %} {% endblock %}</title>
      <script src="{% static "js/jquery-3.6.0.min.js" %}"></script>
      {% block scripts %} {% endblock %}
      <link rel="stylesheet" type="text/css" href="{% static "css/responsive.css" %}">

{#      {% block scripts %} {% endblock %}#}
{#    <script src="{% block scripts %} {% endblock %}"></script>#}
{#javascript and jquery should be used in the base html file so that it is also used in other templates using the base#}

  </head>
  <body>

  <div id="header">

    <div id="title-box">
      <img src="{% static "img/dog.png" %}" alt="Logo">
      <h1>Falls Church Dog Park</h1>
      <h2>Sponsoring Volunteer Group for the Falls Church Dog Park</h2>
    </div><!-- #title -->

{#  go to view py to see logic for redirecting for login request, go to models py to see the username and password used#}
      {% if request.session.username %}

      <form id = "Login-box">
          <p>Logged in as <strong>{{ request.session.username }}</strong> | <a href="{% url 'dogs:logout' %}">Log out</a> </p>
      </form>

      {% elif request.session.username2 %}
      <form id = "Login-box">
          <p>Logged in as <strong>{{ request.session.username2 }}</strong> | <a href="{% url 'dogs:logout2' %}">Log out</a> </p>
      </form>

      {% else %}
{#          login box uses the url for login in views py#}
    <form id = "Login-box" action="{% url "dogs:login" %}" method="POST">
{#        csrf cros site request forgery protection- security measure to prevent site from being hijacked#}
        {% csrf_token %}
      <input type="text" name="username" placeholder="Username">
      <input type="password" name="pw" placeholder="Password">
      <input type="submit" name="submit" value="Log in"> or <a href="#">Register</a>
    </form>

      {% endif %}

{#  need to update the primary nav so that is uses the urls py like how login is using the url from urls py#}
{#  note how the urls py uses the vies py to render#}
    <ul id="primary-nav">
      <li><a href="{% url "dogs:home" %}">Home</a></li>
      <li><a href="{% url "dogs:lostpost-list" %}" >Lost and Found Pets</a></li>
      <li><a href="{% url "dogs:events" %}">Events</a></li>
      <li><a href="{% url "dogs:parkrules" %}">Park Rules</a></li>
    </ul>

  </div><!-- #header -->

  <div id="content">
{#  should be considered the MAIN#}
    <ul id="side-tabs">

        {% block side-tabs %} {% endblock %}
    </ul>

{#  project5 message#}
    <div id ="lostpost">
        {#    insert message using django template#}
{#    NEED TO ADD MESSAGE FOR OTHER ACTIONS, SUCH AS DELETE OR EDIT OF THE POST#}
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}

      {% block content %} {% endblock %}
    </div>
{#  </div>#}

  <div id="side-bar">
      <div class="extra-padding">

{#          <form onsubmit="return setAction(this)" method="get">#}
        <form action="{% url "dogs:searchresultsblank" %}" method="get">
          <input type="text" name="search-page" placeholder="Type 'dog' to avoid error.">
          <input type="submit" name="Search" value="Search">
        </form>

          {% if request.session.username %}

              <h3 class="lostpost-add"><a href="{% url "dogs:add" %}">Add Lost and Found Post</a></h3>
              {% block detail-edit %} {% endblock %}

          {% elif request.session.username2 %}

              <h3 class="lostpost-add"><a href="{% url "dogs:add" %}">Add Lost and Found Post</a></h3>
{#              {% block detail-edit %} {% endblock %}#}
{#              included both edit and delete in this block for the admin#}
              {% block detail-delete %} {% endblock %}

          {% endif %}

        <a href="#" class="decor"><img src="{% static "img/paw.png" %}" alt="Decor"></a>
        <a href="#" class="decor"><img src="{% static "img/paw.png" %}" alt="Decor"></a>
      </div>

  </div>

  <div id="footer">
      {% block footer %} {% endblock %}
  </div>

  </div>
  </body>
</html>

djangoProject1/templates/dogs/home.html
{% extends "dogs/base.html" %}
{% load static %}
{% load humanize %}

{% block page-title %}Lost Post{% endblock %}

{% block scripts %} <script src="{% static "js/list.js" %}"></script>{% endblock %}

{% block side-tabs %}
{% endblock %}

{% block content %}
    <h2 id="section-heading2">Please register an account and log in for you to post, attend events, and more!</h2>
    <h2 id="section-heading">Welcome to the dog park and the community!</h2>

      <div class="lostpost-story">
<!--        <div class="lostpost-pts">11</div>-->
        <h3 class="lostpost-title">  History and Falls Church Support</h3>
        <p class="lostpost-description"> The dog park was founded in 1999. It receives funding from Falls Church county as well as financial support from generous donors and corporate sponsors.</p>
<!--        <p class="lostpost-byline">Submitted by <a href="#">Jdoe</a> 23 hours ago - <a href="#" class="comments">View 2 comments</a> </p>-->
      </div>

    <div class="lostpost-story">
<!--        <div class="lostpost-pts">3</div>-->
        <h3 class="lostpost-title">Volunteer Organization and How to Join</h3>
        <p class="lostpost-description"> The volunteer organization meets at the dog park the second weekend of every month. To join please contact John Doe and johndoe@email.com</p>
<!--        <p class="lostpost-byline">Submitted by <a href="#">Bsmith</a> 45 hours ago - <a href="#" class="comments">View 6 comments</a> </p>-->
      </div>

{% endblock %}

{% block footer %}
    <p id="footer-nav"><a href="#">Home</a> | <a href="#">About</a> | <a href="#">Privacy</a> | <a href="#">Contact Us</a></p>
    <p id="copyright">Copyright 2021 VT Project. All rights reserved</p>
{% endblock %}

djangoProject1/templates/dogs/lostandfound_post/add.html
{% extends "dogs/base.html" %}
{% load static %}
{% load humanize %}

{% block page-title %}Lost Post{% endblock %}

{% block scripts %} <script src="{% static "js/list.js" %}"></script>{% endblock %}

{% block styles %}
{#<link rel="stylesheet" type="text/css" href="{% static "css/add_story.css" %}">#}
<link rel="stylesheet" type="text/css" href="{% static "css/responsive.css" %}">
{% endblock %}

{#{% block page-title %} Submit Post {% endblock %}#}

{% block content %}
    <h2 id="section-heading">Submit Lost and Found Post</h2>

    <div class="extra-padding">

         <form id="lostpost-story" action="{% url "dogs:add" %}" method="post">
             <p>* = required.</p>

{#             <label for="add-title">Title*: </label>#}
             <p class="add-title">Title*: </p>
             <input id="post-title" name="post-title" type="text" required></input>

{#             <label for="add-url">URL*: </label>#}
             <p class="add-url">URL*: </p>
             <input id="post-url" name="post-url" type="text" required>

{#             <label for="add-contact">Contact info: </label>#}
             <p class="add-contact">Contact info: </p>
             <input id="post-contact" name="post-contact" type="text">

{#             <label for="add-description">Description: </label>#}
             <p class="add-description">Description: </p>
             <input id="post-description" name="post-description" type="text">

             <input type="submit" name="submit" value="Submit Post">
             {% csrf_token %}

         </form>
    </div>
{% endblock %}

{#{% block detail-delete-edit %} {% endblock %}#}

{% block footer %}
    <p id="footer-nav"><a href="#">Home</a> | <a href="#">About</a> | <a href="#">Privacy</a> | <a href="#">Contact Us</a></p>
    <p id="copyright">Copyright 2021 VT Project. All rights reserved</p>
{% endblock %}

djangoProject1/templates/dogs/lostandfound_post/delete.html
{% extends "dogs/base.html" %}
{% load static %}
{% load humanize %}

{% block page-title %}Lost Post{% endblock %}

{% block scripts %} <script src="{% static "js/list.js" %}"></script>{% endblock %}

{% block styles %}
{#<link rel="stylesheet" type="text/css" href="{% static "css/add_story.css" %}">#}
<link rel="stylesheet" type="text/css" href="{% static "css/responsive.css" %}">
{% endblock %}

{#{% block page-title %} Submit Post {% endblock %}#}

{% block content %}
    <h2 id="section-heading">Delete Lost and Found Post</h2>

    <div class="extra-padding">

        <form name="delete" id="delete-form" action="{% url "dogs:story-deletefromdatabase" %}" method="POST">

            <div class="lostpost-story">
                <p class="lostpost-title"> Post Title: {{ story.title }}</p>
                <p class="lostpost-url"> Post URL: {{ story.url }}</p>
                <p class="lostpost-description"> Post Description: {{ story.description }}</p>
                <p class="lostpost-contact2"> Contact Info: {{ story.contact }}</p>
            </div>

            <label for="add-title">Press button to delete Lost and Found post selected.</label>
{#            <button class="delete" data-story-id="{{ story.id }}" data-ajax-url="{% url "dogs:story-deletefromdatabase" %}">Delete</button>#}
            <button id="delete" type="submit" class="delete" form="delete-form" formmethod="post">Delete</button>
            {% csrf_token %}

            <input type="hidden" name="id" value="{{ story.id }}">
{#            <input type="hidden" name="title" value="{{ story.title }}">#}
{#            <input type="hidden" name="description" value="{{ story.description }}">#}


{#            PROJECT 5 FORM UNCOMMENT#}
{#             <div class="post-button">#}
{#                 <p class="lostpost-byline"><a href="#" class="postbutton-delete">Delete This Post</a> </p>#}
{#                 <input type="submit" name="postbutton-create" value="Submit story">#}
{#             </div>#}
         </form>
    </div>
{% endblock %}

{#{% block detail-delete-edit %} {% endblock %}#}

{% block footer %}
    <p id="footer-nav"><a href="#">Home</a> | <a href="#">About</a> | <a href="#">Privacy</a> | <a href="#">Contact Us</a></p>
    <p id="copyright">Copyright 2021 VT Project. All rights reserved</p>
{% endblock %}

djangoProject1/templates/dogs/lostandfound_post/edit.html
{% extends "dogs/base.html" %}
{% load static %}
{% load humanize %}

{% block page-title %}Lost Post{% endblock %}

{% block scripts %} <script src="{% static "js/list.js" %}"></script>{% endblock %}

{% block content %}
    <h2 id="section-heading">Edit Lost and Found Post</h2>

    <div class="lostpost-story">
        <p class="lostpost-title"> Post Title: {{ story.title }}</p>
        <p class="lostpost-url"> Post URL: {{ story.url }}</p>
        <p class="lostpost-description"> Post Description: {{ story.description }}</p>
        <p class="lostpost-contact2"> Contact Info: {{ story.contact }}</p>
{#        <p class="lostpost-byline">Submitted by <a href="#">{{ story.author }}</a> </p>#}
    </div>
    <h2 id="section-heading">Update post with input values and click Edit button.</h2>

    <div class="extra-padding">
        <form name="edit" id="edit-form" action="{% url "dogs:story-editfromdatabase" %}" method="POST">

            <input type="hidden" name="id" value="{{ story.id }}">
{#            <input type="hidden" name="title" value="{{ story.title }}">#}
{#            <input type="hidden" name="description" value="{{ story.description }}">#}
{##}
            <p><label for="input-title">Title:*</label>
                <input id="input-title" name="input-title" type="text" value="{{ story.title }}" required></p>

            <p><label for="input-url">URL:*</label>
                <input id="input-url" name="input-url" type="text" value="{{ story.url }} " required></p>

            <p><label for="input-description">Description:</label>
                <input id="input-description" name="input-description" type="text" value="{{ story.description }}"></p>

            <p><label for="input-contact">Contact Info:</label>
                <input id="input-contact" name="input-contact" type="text" value="{{ story.contact }}" ></p>


            <button id="edit" type="submit" class="edit" form="edit-form" formmethod="post">Edit</button>
            {% csrf_token %}

        </form>
    </div>
{% endblock %}


{% block footer %}
    <p id="footer-nav"><a href="#">Home</a> | <a href="#">About</a> | <a href="#">Privacy</a> | <a href="#">Contact Us</a></p>
    <p id="copyright">Copyright 2021 VT Project. All rights reserved</p>
{% endblock %}

djangoProject1/templates/dogs/lostandfound_post/events.html
{% extends "dogs/base.html" %}
{% load static %}
{% load humanize %}

{% block page-title %}Lost Post{% endblock %}

{% block scripts %} <script src="{% static "js/list.js" %}"></script>{% endblock %}

{% block side-tabs %}
{% endblock %}

{% block content %}
      <h2 id="section-heading">Please join us for all of our upcoming community events!</h2>

      <div class="lostpost-story">

<!--        will only color code the recent event additions with the radio button-->
        <div class="lostpost-attendancepts">

            {% if request.session.username %}
                <div class="attendancescore">2</div>
                <button class="attend">Attend</button>

            {% elif request.session.username2 %}
                <div class="attendancescore">2</div>
                <button class="attend">Attend</button>

          {% endif %}


        </div>
        <li class="redevent">
        <h2 class="lostpost-title2">  Event: Great Dane Meetup</h2>
        <p class="lostpost-description2">Date: 2021-09-30 </p>

      </div>

    <div class="lostpost-story">

      <div class="lostpost-attendancepts">

          {% if request.session.username %}
              <div class="attendancescore">2</div>
              <button class="attend">Attend</button>

            {% elif request.session.username2 %}
                <div class="attendancescore">2</div>
                <button class="attend">Attend</button>

          {% endif %}
      </div>

      <li class="greenevent">
      <h2 class="lostpost-title2">Event: Volunteer Group Saturday Meet Up</h2>
      <p class="lostpost-description2">Date: 2021-09-11 </p>
      </div>
<!--end of hardcoded events-->
{% endblock %}

{% block footer %}
    <p id="footer-nav"><a href="#">Home</a> | <a href="#">About</a> | <a href="#">Privacy</a> | <a href="#">Contact Us</a></p>
    <p id="copyright">Copyright 2021 VT Project. All rights reserved</p>
{% endblock %}

djangoProject1/templates/dogs/lostandfound_post/index.html
{% extends "dogs/base.html" %}
{% load static %}
{% load humanize %}

{% block page-title %}Lost Post{% endblock %}

{% block scripts %} <script src="{% static "js/list.js" %}"></script>{% endblock %}

{% block side-tabs %}
{% endblock %}

{% block content %}
    <h2 id="section-heading">Welcome to the dog park and the community!</h2>

      <div class="lostpost-story">
<!--        <div class="lostpost-pts">11</div>-->
        <h3 class="lostpost-title">  History and Falls Church Support</h3>
        <p class="lostpost-description"> The dog park was founded in 1999. It receives funding from Falls Church county as well as financial support from generous donors and corporate sponsors.</p>
<!--        <p class="lostpost-byline">Submitted by <a href="#">Jdoe</a> 23 hours ago - <a href="#" class="comments">View 2 comments</a> </p>-->
      </div>

    <div class="lostpost-story">
<!--        <div class="lostpost-pts">3</div>-->
        <h3 class="lostpost-title">Volunteer Organization and How to Join</h3>
        <p class="lostpost-description"> The volunteer organization meets at the dog park the second weekend of every month. To join please contact John Doe and johndoe@email.com</p>
<!--        <p class="lostpost-byline">Submitted by <a href="#">Bsmith</a> 45 hours ago - <a href="#" class="comments">View 6 comments</a> </p>-->
      </div>

{% endblock %}

{% block footer %}
    <p id="footer-nav"><a href="#">Home</a> | <a href="#">About</a> | <a href="#">Privacy</a> | <a href="#">Contact Us</a></p>
    <p id="copyright">Copyright 2021 VT Project. All rights reserved</p>
{% endblock %}

djangoProject1/templates/dogs/lostandfound_post/list.html
{% extends "dogs/base.html" %}
{% load static %}
{% load humanize %}

{% block page-title %}Lost Post{% endblock %}

{% block scripts %} <script src="{% static "js/list.js" %}"></script>{% endblock %}
{# jquery file already included in the base html file - js/jquery-3.6.0.min.js#}

{% block side-tabs %}
{#    <li><a href="{% url "dogs:lostpost-list" %}" >Lost and Found Pets</a></li>#}
    <li>Sort by:</li>
    <li><a href="{% url "dogs:lostpost-list" %}">Popular (Votes Descending)</a> </li>
    <li><a href="{% url "dogs:lostpost-list-date" %}">Newest (Date Ascending)</a> </li>
    <li><a href="{% url "dogs:lostpost-list-date2" %}">Oldest (Date Descending)</a> </li>
{% endblock %}

{% block content %}
{#    insert message using django template, use this in base html#}
{#    {% if messages %}#}
{#    <ul class="messages">#}
{#        {% for message in messages %}#}
{#        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>#}
{#        {% endfor %}#}
{#    </ul>#}
{#    {% endif %}#}

    <h2 id="section-heading">Lost and Found</h2>
    <li>Posts can be sorted by score or date posted</li>
    {#    <h2 id="section-heading">*Posts can be sorted by score or date posted</h2>#}

{#    PROJECT5 SORT DROPDOWN FOR SORTING USIGN AJAX#}
{#      AJAX IN LIST.JS USES NAME "sort" #}
            <div class="list-sorter">
{#                <label for="sort">Sort By:</label>#}
{#                <select name="sort" id="sort" data-ajax-url="{% url "dogs:list_sort_ajax" %}">#}
{#                    <option value="score" selected>Score</option>#}
{#                    <option value="posted-date">Posted Date</option>#}
{#                </select>#}
            </div>

{#for passing the views.py lostpost_list that is using the models.py#}
    {% for story in stories %}
{#    PROJECT5 count message if empty#}
        {% if stories.count == 0%}
            <p class="message"><strong>There are no posts right now!</strong></p>
        {% else %}

        <div class="lostpost-story">

            <div class="lostpost-pts">

                {% if request.session.username %}

{#                    NEED TO UPDATE UPVOTE FOR BOTH USERS!!!#}
{#                    <button class="upvote">Upvote</button>#}
                    <button class="upvote" data-story-id="{{ story.id }}" data-ajax-url="{% url "dogs:story-upvote" %}">Upvote</button>

                {% elif request.session.username2 %}

                    <button class="upvote" data-story-id="{{ story.id }}" data-ajax-url="{% url "dogs:story-upvote" %}">Upvote</button>

                {%  endif %}

                <div class="score">{{ story.score }}</div>

                {% if request.session.username %}

{#                    <button class="upvote" data-story-id="{{ story.id }}" data-ajax-url="{% url "dogs:story-upvote" %}">Upvote</button>#}
                    <button class="downvote" data-story-id="{{ story.id }}" data-ajax-url="{% url "dogs:story-downvote" %}">Downvote</button>

                {% elif request.session.username2 %}

{#                    <button class="downvote">Downvote</button>#}
                    <button class="downvote" data-story-id="{{ story.id }}" data-ajax-url="{% url "dogs:story-downvote" %}">Downvote</button>
                {% endif %}

            </div>
                <h3 class="lostpost-title"><a href="{{ story.url }}"> {{ story.title }}</a></h3>

            {% if request.session.username %}

                <p class="lostpost-byline2"><a href="{% url "dogs:story-edit" story.id %}">Edit Post</a></p>

            {% elif request.session.username2 %}

                <p class="lostpost-byline2"><a href="{% url "dogs:story-edit" story.id %}">Edit Post</a></p>
                <p class="lostpost-byline2"><a href="{% url "dogs:story-delete" story.id %}">Delete Post</a></p>

            {% endif %}
        {% endif %}

{#        PROJCT 5 SORT BY date_posted, use the side tabs on the left!#}
                <p class="date_posted" > {{ story.date_posted }}</p>
                <p class="lostpost-description"> {{ story.description }}</p>

{#        PROJECT5 USES AJAX TO GET THE CONTACT INFO! DETAIL VIEW FOR lostpost-contactinfo#}
{#                <p class="lostpost-contact"> <b> Contact info: {{ story.contact }} </b></p>#}

        {#        update the comments url on the list.html so that it dynamically links to the story details page for the story#}
        {#        need to reference the app of dogs, used in the url.py#}
                <p class="lostpost-byline">Submitted by <a href="#">{{ story.author }}</a> {{ story.date_posted|naturaltime }} - <a href="{% url "dogs:story-detail" story.id %}" class="comments">View comments and detail view</a> </p>
        </div>


    {% endfor %}

{% endblock %}

{% block footer %}
    <p id="footer-nav"><a href="#">Home</a> | <a href="#">About</a> | <a href="#">Privacy</a> | <a href="#">Contact Us</a></p>
    <p id="copyright">Copyright 2021 VT Project. All rights reserved</p>
{% endblock %}

djangoProject1/templates/dogs/lostandfound_post/parkrules.html
{% extends "dogs/base.html" %}
{% load static %}
{% load humanize %}

{% block page-title %}Lost Post{% endblock %}

{% block scripts %} <script src="{% static "js/list.js" %}"></script>{% endblock %}

{% block side-tabs %}
{% endblock %}

{% block content %}
  <h2 id="section-heading">Please Follow Park Rules and Contact Department of Animal Control to Report Bites and Attacks</h2>

      <div class="lostpost-story">
<!--        <div class="lostpost-pts">11</div>-->
        <h3 class="lostpost-title">  Rules and Regulations</h3>
        <p class="lostpost-description"> Mandated by Falls Church Dog Park, Punishable by Falls Church</p>
<!--        <p class="lostpost-byline">Submitted by <a href="#">Jdoe</a> 23 hours ago - <a href="#" class="comments">View 2 comments</a> </p>-->
            <ul>
                <li>All dogs must be licensed and vaccinated before entering the Dog Park.</li>
                <li>Both rabies vaccinations tags and Dog License tags are required to be secured on your dog at all times.</li>
                <li>No dogs less than four (4) months of age shall be permitted in a Dog Park.</li>
                <li>Handlers / guardians are responsible for removing dog waste from the Park and disposing it in a proper receptacle.</li>
                <li>Dogs must be leashed when entering and exiting the Dog Park.</li>
                <li>Violations of the leash law, running at large law and not picking up after your dog can result in a summons to appear in court and a $100.00 fine.</li>
            </ul>
      </div>

        <div class="lostpost-story">
    <!--        <div class="lostpost-pts">3</div>-->
            <h3 class="lostpost-title">Dog Park Map</h3>
            <p class="lostpost-description"><a href="https://parks.arlingtonva.us/parksfacilities/dog-parks/">Please follow link to map of dog park on county site.</a> </p>
    <!--        <p class="lostpost-byline">Submitted by <a href="#">Bsmith</a> 45 hours ago - <a href="#" class="comments">View 6 comments</a> </p>-->

        </div>
<!--end of hardcoded events-->
{% endblock %}

{% block footer %}
    <p id="footer-nav"><a href="#">Home</a> | <a href="#">About</a> | <a href="#">Privacy</a> | <a href="#">Contact Us</a></p>
    <p id="copyright">Copyright 2021 VT Project. All rights reserved</p>
{% endblock %}

djangoProject1/templates/dogs/lostandfound_post/searchresults.html
{% extends "dogs/base.html" %}
{% load static %}
{% load humanize %}

{% block page-title %}Lost Post{% endblock %}

{% block scripts %} <script src="{% static "js/list.js" %}"></script>{% endblock %}

{% block side-tabs %}
{% endblock %}

{% block content %}
 <h2 id="section-heading">Search results:</h2>

        <h3 class="lostpost-title"><a href="https://www.awla.org/services/for-you/lost-found/found-animals/"> Lost Dog</a></h3>
        <p class="lostpost-description"> My dog is missing. Please help!</p>
        <p class="lostpost-byline">Submitted by <a href="#">Bsmith</a> 45 hours ago </p>

{% endblock %}

{% block footer %}
    <p id="footer-nav"><a href="#">Home</a> | <a href="#">About</a> | <a href="#">Privacy</a> | <a href="#">Contact Us</a></p>
    <p id="copyright">Copyright 2021 VT Project. All rights reserved</p>
{% endblock %}

djangoProject1/templates/dogs/lostandfound_post/searchresultsblank.html
{% extends "dogs/base.html" %}
{% load static %}
{% load humanize %}

{% block page-title %}Lost Post{% endblock %}

{% block scripts %} <script src="{% static "js/list.js" %}"></script>{% endblock %}

{% block side-tabs %}
{% endblock %}

{% block content %}
 <h2 id="section-heading">Search results:</h2>

{#    no search results in output#}

{% endblock %}

{% block footer %}
    <p id="footer-nav"><a href="#">Home</a> | <a href="#">About</a> | <a href="#">Privacy</a> | <a href="#">Contact Us</a></p>
    <p id="copyright">Copyright 2021 VT Project. All rights reserved</p>
{% endblock %}